### ISSUE TITLE
question about branches

### ISSUE THREAD

**Issue by rubydesign** [GirlsCodersWarsaw/CodeQuestProject_Basia#3]
How come there are so many branches, several unsused? 
And why is main development not happening on master? 
It makes it difficult to see what you are doing (one has to know which branch you are actually working on).

**Comment by aberracja** [comment]
ok then, I have to do my homework with git :)
I'll start for this:
https://www.atlassian.com/git/tutorials/using-branches
https://guides.github.com/introduction/flow/

If you guys have any better articles about git feel free to add it in comments.

/cc @pjar @lsolniczek

**Comment by rubydesign** [comment]
Basia, those were questions i asked (not rhetoric), could you answer them please.
I would suggest you talk to your coaches and develop on the master branch.
Branches a little advanced and not really a topic for the first week. Maybe later.
You should code as much as possible to get into the flow of things.

**Comment by aberracja** [comment]
Torsten, sure!
1. right now I'm working on feature/projects, and it's ready to merge with develop what I'm going to do today. I don't use rest of feature branches and I have to delete them.
2. I was told to work on feature branches and merge it with develop. I'm not sure why not with master. Maybe because I haven't tested yet?

Should I develop on master branch? 
/cc @pjar @lsolniczek

**Comment by aberracja** [comment]
we've agreed with coaches that we should use master, develop and feature branches created from develop. Develop before master - just to be sure that everything is good.
